### ISSUE TITLE
when Manually Setup openyurt, /var/lib/openyurt/kubelet.conf will reset after restart kubelet.service

### ISSUE THREAD

**Issue by carolove** [alibaba/openyurt#103]
steps:
1、follow https://github.com/alibaba/openyurt/blob/master/docs/tutorial/manually-setup.md
2、at the last  step
https://github.com/alibaba/openyurt/blob/master/docs/tutorial/manually-setup.md#reset-the-kubelet
i set kubeconfig(/var/lib/openyurt/kubelet.conf), like below:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:10261
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: default-auth
```

3、after reset kubelet.service, kubeconfig(/var/lib/openyurt/kubelet.conf) return the original one, 

how do your guys keep kubeconfig into the correct one?
